增加了 batch_update 方法
TIOJ-INFOR-Online-Judge/tioj pull request #32
Opened 2024-03-24 15:43 UTC by william1010121

新增了以下的功能
1. 在 problem testdata 裡面有增加了batch_update 的方法
2. batch_update 有如下限制和功能
- 只能上傳 .in, .out 為結尾的檔名（可以一次全選上傳，程式會自動找出 .in, .out file 並且排序分類）
-   .in, .out 的輸入檔案名稱需要對應（ ex: a123.in, a123.out )
- 有 input/output list file info 可以確認配對情況
- 上傳的時候會打包成 .zip 檔案
- 在後端會解壓縮，並且在操作完成之後刪除 temp floder

2024-03-24 15:50 UTC, oToToT commented on yarn-error.log
should be removed.

2024-03-24 15:50 UTC, oToToT commented on testinfiles0.in
ditto

2024-03-24 15:52 UTC, oToToT requested changes

2024-03-24 15:52 UTC, oToToT commented on testoutfiles0.out
ditto

2024-03-24 15:52 UTC, oToToT commented on docker-compose.yml
ditto

2024-03-24 15:52 UTC, oToToT commented on config/environments/development.rb
ditto

2024-03-24 15:52 UTC, oToToT commented on app/views/testdata/batch_edit.html.erb
ditto

2024-03-24 15:53 UTC, oToToT commented
Thanks for contributing!

2024-03-24 15:56 UTC, william1010121 commented
我整理一下 commit ，晚點再上傳，不然好像太亂了

2024-03-24 20:47 UTC, adrien1018 commented
rebase 把 log file 從 commit history 裡面拿掉，然後把 problem import 的部分也拿掉（這部份看你要不要發新 PR）應該就 ok 了
我會把它跟 esbuild 整合之後跟 3.1.0 版本一起 release

2024-03-26 06:29 UTC, william1010121 commented
進行了如下修改
1. 將 log file 都刪除了
2. 移除了 import problem 的相關內容
3. 增加了 .zip 檔案的確認

2024-03-28 03:16 UTC, merged